"""
错误码模块

统一错误码枚举，覆盖身份、授权、支付、存证等全部错误码。
"""

from enum import Enum


class ErrorCode(str, Enum):
    # ========== 身份与绑定 ==========
    IDENTITY_NOT_FOUND = "IDENTITY_NOT_FOUND"
    INVALID_CREDENTIAL = "INVALID_CREDENTIAL"
    CREDENTIAL_EXPIRED = "CREDENTIAL_EXPIRED"
    CREDENTIAL_SUSPENDED = "CREDENTIAL_SUSPENDED"
    CREDENTIAL_REVOKED = "CREDENTIAL_REVOKED"
    USER_AGENT_BINDING_INVALID = "USER_AGENT_BINDING_INVALID"
    PAYMENT_BINDING_INVALID = "PAYMENT_BINDING_INVALID"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    SESSION_IDENTITY_MISMATCH = "SESSION_IDENTITY_MISMATCH"

    # ========== 智能体交互 ==========
    INVALID_INTERACTION_ENVELOPE = "INVALID_INTERACTION_ENVELOPE"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    MESSAGE_REPLAYED = "MESSAGE_REPLAYED"
    SENDER_MISMATCH = "SENDER_MISMATCH"
    TASK_STATE_ERROR = "TASK_STATE_ERROR"

    # ========== 委托授权 ==========
    INTENT_NOT_CONFIRMED = "INTENT_NOT_CONFIRMED"
    INVALID_IAC = "INVALID_IAC"
    IAC_EXPIRED = "IAC_EXPIRED"
    IAC_SUSPENDED = "IAC_SUSPENDED"
    IAC_REVOKED = "IAC_REVOKED"
    AGENT_ID_MISMATCH = "AGENT_ID_MISMATCH"
    INVALID_DELEGATION_MODE = "INVALID_DELEGATION_MODE"

    # ========== 商业交互 ==========
    SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    INVALID_SERVICE_INPUT = "INVALID_SERVICE_INPUT"
    PRICE_EXPIRED = "PRICE_EXPIRED"
    RESOURCE_EXPIRED = "RESOURCE_EXPIRED"
    SERVICE_DEPENDENCY_MISSING = "SERVICE_DEPENDENCY_MISSING"

    # ========== 支付 ==========
    REQUEST_REPLAYED = "REQUEST_REPLAYED"
    REQUEST_EXPIRED = "REQUEST_EXPIRED"
    INVALID_AGENT_SIGNATURE = "INVALID_AGENT_SIGNATURE"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    SELLER_NOT_ALLOWED = "SELLER_NOT_ALLOWED"
    CATEGORY_NOT_ALLOWED = "CATEGORY_NOT_ALLOWED"
    SINGLE_LIMIT_EXCEEDED = "SINGLE_LIMIT_EXCEEDED"
    TOTAL_LIMIT_EXCEEDED = "TOTAL_LIMIT_EXCEEDED"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    RESOURCE_MISMATCH = "RESOURCE_MISMATCH"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
    PROOF_INVALID = "PROOF_INVALID"
    PROOF_EXPIRED = "PROOF_EXPIRED"
    PROOF_ALREADY_USED = "PROOF_ALREADY_USED"
    TRADE_STATE_ERROR = "TRADE_STATE_ERROR"

    # ========== 存证 ==========
    INVALID_EVENT_TYPE = "INVALID_EVENT_TYPE"
    INVALID_ATTESTATION_STRUCTURE = "INVALID_ATTESTATION_STRUCTURE"
    INVALID_PAYLOAD_HASH = "INVALID_PAYLOAD_HASH"
    INVALID_ATTESTATION_SIGNATURE = "INVALID_ATTESTATION_SIGNATURE"
    TRACE_LINK_MISMATCH = "TRACE_LINK_MISMATCH"
    ATTESTATION_NOT_FOUND = "ATTESTATION_NOT_FOUND"
    ATTESTATION_SUBMISSION_FAILED = "ATTESTATION_SUBMISSION_FAILED"


class AppError(Exception):
    """统一应用异常，携带错误码。"""

    def __init__(self, code: ErrorCode, message: str = ""):
        self.code = code
        self.message = message or code.value
        super().__init__(f"[{code.value}] {self.message}")
